### ISSUE TITLE
Crash on SNV module

### ISSUE THREAD

**Issue by adbeggs** [fritzsedlazeck/Spectre#21]
First attempt since my last round of queries... running with Clair3 SNVs and get:

```
Traceback (most recent call last):
  File "/rds/projects/b/beggsa-clinicalnanopore/software/condaenvs/spectre2/bin/spectre", line 8, in <module>
    sys.exit(main())
  File "/rds/projects/b/beggsa-clinicalnanopore/software/condaenvs/spectre2/lib/python3.10/site-packages/spectre/spectre.py", line 614, in main
    spectre_run.spectre_exe()
  File "/rds/projects/b/beggsa-clinicalnanopore/software/condaenvs/spectre2/lib/python3.10/site-packages/spectre/spectre.py", line 349, in spectre_exe
    spectre_main.cnv_call()
  File "/rds/projects/b/beggsa-clinicalnanopore/software/condaenvs/spectre2/lib/python3.10/site-packages/spectre/spectreCNV.py", line 70, in cnv_call
    self.snv_analysis.snv_copy_number_state()
  File "/rds/projects/b/beggsa-clinicalnanopore/software/condaenvs/spectre2/lib/python3.10/site-packages/spectre/analysis/snv_analysis.py", line 230, in snv_copy_number_state
    self.snv_multimodal_detect()
  File "/rds/projects/b/beggsa-clinicalnanopore/software/condaenvs/spectre2/lib/python3.10/site-packages/spectre/analysis/snv_analysis.py", line 103, in snv_multimodal_detect
    self.het_dump()
  File "/rds/projects/b/beggsa-clinicalnanopore/software/condaenvs/spectre2/lib/python3.10/site-packages/spectre/analysis/snv_analysis.py", line 131, in het_dump
    het_dump_file = gzip.open(f'{self.spectre_args.out_dir}/debug/het_dump.txt.gz', 'wt')
  File "/rds/projects/b/beggsa-clinicalnanopore/software/condaenvs/spectre2/lib/python3.10/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/rds/projects/b/beggsa-clinicalnanopore/software/condaenvs/spectre2/lib/python3.10/gzip.py", line 174, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/rds/projects/b/beggsa-clinicalnanopore/to_share_via_globus/Rare_Disease_Hannah_Titherage_200623/D2325440/20230620_0810_3E_PAO44618_97828260/spectre2a/debug/het_dump.txt.gz'
```

**Comment by philippesanio** [comment]
Hi @adbeggs 

Which install did you use for Spectre pip or the local installation?
This issue has been fixed two commits ago (0e96275) and is already part of the local installation. The changes will be part of the new pip version 0.2.1. However, the new version will be pushed after we have addressed some changes to the population mode.

Local installation with pip:
```bash
pip install build
git clone https://github.com/fritzsedlazeck/Spectre.git
cd ./Spectre
python3 -m build
pip install dist/spectre-cnv-<VERSION>.tar.gz # replace <VERSION> with e.g. 0.2.0
```

Please let me know if that fixed the issue for the time being.
Thanks,
Philippe

**Comment by adbeggs** [comment]
Hi Phillipe

My bad, must have missed a commit, I will try again

A

**Comment by philippesanio** [comment]
Hi @adbeggs 

Just wanted to check if the new Spectre version 0.2.1 fixed your issues?

Cheers,
Philippe
